name: fetch-oi-futures

on:
  schedule:
    - cron: '*/15 9-15 * * 1-5'  # Every 15 min from 9:00 to 15:45 IST (converted to UTC)
  workflow_dispatch:

jobs:
  fetch-and-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetch_futures_oi.py
        env:
          ZERODHA_API_KEY: ${{ secrets.ZERODHA_API_KEY }}
          ZERODHA_ACCESS_TOKEN: ${{ secrets.ZERODHA_ACCESS_TOKEN }}
          SERVICE_ACCOUNT_JSON_B64: ${{ secrets.SERVICE_ACCOUNT_JSON_B64 }}
        run: |
          python fetch_futures_oi.py
